inova.0133.1 inova 133 1 dat 133_ricahypo dat F 65 4 ipsilateral none CNIII_palsy xxx xxx xxx xxx xxx xxx A R ICA SHYP xxx LAT GR grow MULTIPLE YES OLD ICA-SHYP R RUPTURED
inova.0135.5 inova 135 5 dat 135_lpcom dat F 44 5 ipsilateral none none xxx xxx xxx xxx xxx xxx A L PCOM xxx xxx LAT R xxx MULTIPLE NO MIDDLE PCOM R RUPTURED
inova.0214.3 inova 214 3 dat 214_rpcom dat F 52 3 ipsilateral none none xxx xxx xxx xxx xxx xxx A R PCOM xxx xxx BIF R xxx MULTIPLE NO MIDDLE PCOM R RUPTURED
inova.0293.1 inova 293 1 dat 293_acom dat M 28 2 ipsilateral none none xxx xxx xxx xxx xxx xxx A L ACOM xxx xxx BIF R xxx MULTIPLE NO YOUNG ACOM R RUPTURED
inova.0327.2 inova 327 2 dat 327_rmcabif dat F 44 2 ipsilateral none none xxx xxx xxx xxx xxx xxx A R MCA BIF xxx BIF R xxx MULTIPLE NO MIDDLE MCA-BIF R RUPTURED
inova.0384.1 inova 384 1 dat 384_acom dat M 45 2 ipsilateral none none xxx xxx xxx xxx xxx xxx A L ACOM xxx xxx BIF R xxx MULTIPLE NO MIDDLE ACOM R RUPTURED
inova.1156.2 inova 1156 2 pdb0 156 no F 58 2 ipsilateral none xxx xxx xxx xxx xxx xxx xxx A R ICA SHYP xxx FUS R xxx MULTIPLE xxx MIDDLE ICA-SHYP R RUPTURED
inova.1226.1 inova 1226 1 pdb0 226 no F 53 4 ipsilateral opposite xxx xxx xxx xxx xxx xxx xxx A L MCA BIF large BIF R guess MULTIPLE xxx MIDDLE MCA-BIF R RUPTURED
inova.2264.1 inova 2264 1 pdb1 PATIENT0264 no F 63 2 ipsilateral none xxx xxx xxx xxx xxx xxx xxx A L PCOM xxx xxx BIF R xxx MULTIPLE xxx OLD PCOM R RUPTURED
inova.2301.2 inova 2301 2 pdb1 PATIENT0301 no F 63 2 ipsilateral none xxx xxx xxx xxx xxx xxx xxx A L PCOM xxx xxx BIF R xxx MULTIPLE xxx OLD PCOM R RUPTURED
inova.2331.1 inova 2331 1 pdb1 PATIENT0331 no M 50 2 ipsilateral none xxx xxx xxx xxx xxx xxx xxx A BILAT ACOM xxx xxx BIF R xxx MULTIPLE xxx MIDDLE ACOM R RUPTURED
inova.2370.1 inova 2370 1 pdb1 PATIENT0370 no F 55 3 ipsilateral none xxx xxx xxx xxx xxx xxx xxx A R MCA BIF xxx BIF R xxx MULTIPLE xxx MIDDLE MCA-BIF R RUPTURED
inova.2404.1 inova 2404 1 pdb1 PATIENT0404 no F 48 4 ipsilateral none xxx xxx xxx xxx xxx xxx xxx A R ACOM xxx xxx BIF R RMCA_bif_+_RPCOM_+_ACOM_+_RACA_peric_______ MULTIPLE xxx MIDDLE ACOM R RUPTURED
inova.2455.1 inova 2455 1 pdb1 PATIENT0455 no F 74 2 ipsilateral none xxx xxx xxx xxx xxx xxx xxx A L ACOM xxx xxx BIF R xxx MULTIPLE xxx OLD ACOM R RUPTURED
inova.2493.1 inova 2493 1 pdb1 PATIENT0493 no F 58 3 ipsilateral none xxx xxx xxx xxx xxx xxx xxx A BILAT ACOM xxx xxx LAT R complicated_by_intraprocedural_extravasation_–_lpcom_infund MULTIPLE xxx MIDDLE ACOM R RUPTURED
inova.2640.1 inova 2640 1 pdb1 PATIENT0640 no F 28 2 ipsilateral none xxx xxx xxx xxx xxx xxx xxx A L PCOM xxx xxx BIF R xxx MULTIPLE xxx YOUNG PCOM R RUPTURED
inova.2645.1 inova 2645 1 pdb1 PATIENT0645 no M 76 2 ipsilateral none xxx xxx xxx xxx xxx xxx xxx A L MCA BIF xxx BIF R proximal_stenosis MULTIPLE xxx OLD MCA-BIF R RUPTURED
inova.3043.1 inova 3043 1 pdb2 PATIENT0043 no F 48 2 ipsilateral none xxx xxx xxx xxx xxx xxx xxx A R ICA SHYP xxx LAT R xxx MULTIPLE xxx MIDDLE ICA-SHYP R RUPTURED
inova.3144.1 inova 3144 1 pdb2 PATIENT0144 no F 59 3 ipsilateral none xxx xxx xxx xxx xxx xxx xxx A R ACOM xxx xxx BIF R init MULTIPLE xxx MIDDLE ACOM R RUPTURED
inova.3170.1 inova 3170 1 pdb2 PATIENT0170 no F 68 2 ipsilateral opposite xxx xxx xxx xxx xxx xxx xxx A R ICA SHYP xxx LAT R init MULTIPLE xxx OLD ICA-SHYP R RUPTURED
inova.3214.1 inova 3214 1 pdb2 PATIENT0214 no F 62 3 ipsilateral opposite xxx xxx xxx xxx xxx xxx xxx A R MCA BIF large BIF R xxx MULTIPLE xxx OLD MCA-BIF R RUPTURED
inova.3228.1 inova 3228 1 pdb2 PATIENT0228 no F 41 2 ipsilateral none xxx xxx xxx xxx xxx xxx xxx A R ICA OPH xxx LAT R xxx MULTIPLE xxx MIDDLE ICA-OPH R RUPTURED
inova.3229.1 inova 3229 1 pdb2 PATIENT0229 no F 66 6 ipsilateral none xxx xxx xxx xxx xxx xxx xxx A R PCOM xxx xxx BIF R xxx MULTIPLE xxx OLD PCOM R RUPTURED
inova.4290.1 inova 4290 1 pdb3 PATIENT0290 no F 50 2 ipsilateral none xxx xxx xxx xxx xxx xxx xxx A L MCA BIF xxx BIF R xxx MULTIPLE xxx MIDDLE MCA-BIF R RUPTURED
inova.4302.1 inova 4302 1 pdb3 PATIENT0302 no xxx xxx 2 ipsilateral none xxx xxx xxx xxx xxx xxx xxx A R ICA SHYP xxx LAT R xxx MULTIPLE xxx xxx ICA-SHYP R RUPTURED
inova.4347.1 inova 4347 1 pdb3 PATIENT0347 no F 54 3 ipsilateral none xxx xxx xxx xxx xxx xxx xxx A L ACOM xxx xxx BIF R xxx MULTIPLE xxx MIDDLE ACOM R RUPTURED
inova.4355.1 inova 4355 1 pdb3 PATIENT0355 no M 64 3 ipsilateral none xxx xxx xxx xxx xxx xxx xxx A R ACOM xxx xxx BIF R guess MULTIPLE xxx OLD ACOM R RUPTURED
inova.4367.1 inova 4367 1 pdb3 PATIENT0367 no M 46 2 ipsilateral none xxx xxx xxx xxx xxx xxx xxx A R ICA OPH xxx LAT R xxx MULTIPLE xxx MIDDLE ICA-OPH R RUPTURED
inova.4371.1 inova 4371 1 pdb3 PATIENT0371 no M 73 2 ipsilateral none xxx xxx xxx xxx xxx xxx xxx A R ACOM xxx xxx BIF R xxx MULTIPLE xxx OLD ACOM R RUPTURED
inova.4380.1 inova 4380 1 pdb3 PATIENT0380 no F 85 2 ipsilateral none xxx xxx xxx xxx xxx xxx xxx A L PCOM xxx xxx BIF R xxx MULTIPLE xxx OLD PCOM R RUPTURED
inova.4440.4 inova 4440 4 pdb3 PATIENT0440 no F 86 5 ipsilateral none xxx xxx xxx xxx xxx xxx xxx A L PCOM xxx xxx BIF R xxx MULTIPLE xxx OLD PCOM R RUPTURED
inova.4445.3 inova 4445 3 pdb3 PATIENT0445 no F 55 3 ipsilateral none xxx xxx xxx xxx xxx xxx xxx A R ACA PERIC xxx BIF R Coiled MULTIPLE xxx MIDDLE ACA-DIST R RUPTURED
sinai.0142.1 sinai 142 1 dat.sinai xxx no M 80 3 ipsilateral none xxx 5 xxx xxx xxx xxx xxx A L ACA PERIC xxx BIF R xxx MULTIPLE xxx OLD ACA-DIST R RUPTURED
sinai.0158.1 sinai 158 1 dat.sinai xxx no M 58 2 ipsilateral none xxx 2 F3 xxx xxx xxx xxx A R ACOM xxx xxx BIF R xxx MULTIPLE xxx MIDDLE ACOM R RUPTURED
sinai.0191.1 sinai 191 1 dat.sinai xxx no M 65 2 ipsilateral none xxx 4 F3 xxx xxx xxx xxx A L ICA OPH ventral LAT R xxx MULTIPLE xxx OLD ICA-OPH R RUPTURED
sinai.0217.1 sinai 217 1 dat.sinai xxx no F 44 2 ipsilateral none xxx 5 xxx xxx xxx xxx xxx A R MCA BIF xxx BIF R xxx MULTIPLE xxx MIDDLE MCA-BIF R RUPTURED
sinai.0226.1 sinai 226 1 dat.sinai xxx no F 48 5 ipsilateral opposite xxx 3 xxx Y xxx xxx HTN A R MCA BIF large BIF R xxx MULTIPLE xxx MIDDLE MCA-BIF R RUPTURED
sinai.0254.1 sinai 254 1 dat.sinai xxx no F 55 3 ipsilateral none xxx xxx xxx xxx xxx xxx xxx A L MCA BIF xxx BIF R xxx MULTIPLE xxx MIDDLE MCA-BIF R RUPTURED
sinai.0255.1 sinai 255 1 dat.sinai xxx no F 60 2 ipsilateral none xxx xxx xxx xxx xxx xxx xxx A R ACOM xxx xxx BIF R proximal_stenosis MULTIPLE xxx MIDDLE ACOM R RUPTURED
sinai.0268.1 sinai 268 1 dat.sinai xxx no F 59 2 ipsilateral none xxx xxx xxx xxx xxx xxx xxx A L ICA OPH xxx BIF R traumatic_after_transspenoidal_meningioma_resection MULTIPLE xxx MIDDLE ICA-OPH R RUPTURED
sinai.0269.1 sinai 269 1 dat.sinai xxx no F 60 2 ipsilateral none xxx 5 xxx xxx xxx xxx xxx A L ACOM xxx xxx BIF R xxx MULTIPLE xxx MIDDLE ACOM R RUPTURED
sinai.0275.1 sinai 275 1 dat.sinai xxx no F 80 2 ipsilateral none xxx xxx xxx xxx xxx xxx xxx A L PCOM xxx xxx BIF R xxx MULTIPLE xxx OLD PCOM R RUPTURED
sinai.0287.1 sinai 287 1 dat.sinai xxx no F 56 2 ipsilateral none xxx xxx xxx xxx xxx xxx xxx A L PCOM xxx xxx BIF R xxx MULTIPLE xxx MIDDLE PCOM R RUPTURED
sinai.0309.1 sinai 309 1 dat.sinai xxx no F 67 2 ipsilateral none xxx xxx xxx xxx xxx xxx xxx A L ICA ACHOR xxx BIF R xxx MULTIPLE xxx OLD ICA-ACHOR R RUPTURED
sinai.0320.1 sinai 320 1 dat.sinai xxx no F 88 3 ipsilateral none xxx xxx xxx xxx xxx xxx xxx A R PCOM xxx proximal BIF R xxx MULTIPLE xxx OLD PCOM R RUPTURED
sinai.0353.1 sinai 353 1 dat.sinai xxx no M 57 2 ipsilateral none xxx xxx xxx xxx xxx xxx xxx A R PCOM xxx xxx BIF R xxx MULTIPLE xxx MIDDLE PCOM R RUPTURED
sinai.0381.1 sinai 381 1 dat.sinai xxx no M 28 3 ipsilateral opposite xxx xxx xxx xxx xxx xxx xxx A L ICA SHYP ventral LAT R xxx MULTIPLE xxx YOUNG ICA-SHYP R RUPTURED
sinai.0382.1 sinai 382 1 dat.sinai xxx no F 65 2 ipsilateral none xxx xxx xxx xxx xxx xxx xxx A L ACOM xxx xxx BIF R xxx MULTIPLE xxx OLD ACOM R RUPTURED
sinai.0386.1 sinai 386 1 dat.sinai xxx no F 68 2 ipsilateral none xxx 4 xxx xxx xxx xxx xxx A L ACOM xxx xxx BIF R xxx MULTIPLE xxx OLD ACOM R RUPTURED
sinai.0399.1 sinai 399 1 dat.sinai xxx no F 55 3 ipsilateral none xxx xxx xxx xxx xxx xxx xxx A R ACOM xxx xxx BIF R xxx MULTIPLE xxx MIDDLE ACOM R RUPTURED
sinai.0410.1 sinai 410 1 dat.sinai xxx no F 46 2 ipsilateral none xxx xxx xxx xxx xxx xxx xxx A L ACOM xxx xxx BIF R xxx MULTIPLE xxx MIDDLE ACOM R RUPTURED
sinai.0417.1 sinai 417 1 dat.sinai xxx no F 83 2 ipsilateral none xxx xxx xxx xxx xxx xxx xxx A R ACOM xxx xxx BIF R xxx MULTIPLE xxx OLD ACOM R RUPTURED
sinai.0422.1 sinai 422 1 dat.sinai xxx no F 47 2 ipsilateral none xxx xxx xxx xxx xxx xxx xxx A R MCA BIF xxx BIF R xxx MULTIPLE xxx MIDDLE MCA-BIF R RUPTURED
sinai.0459.1 sinai 459 1 dat.sinai xxx no F 33 2 ipsilateral none xxx xxx xxx xxx xxx xxx xxx A R ICA SHYP dorsal LAT R xxx MULTIPLE xxx YOUNG ICA-SHYP R RUPTURED
sinai.0463.1 sinai 463 1 dat.sinai xxx no M 45 2 ipsilateral none xxx xxx xxx xxx xxx xxx xxx A R ACOM xxx xxx BIF R xxx MULTIPLE xxx MIDDLE ACOM R RUPTURED
sinai.0494.2 sinai 494 2 dat.sinai xxx no F 73 2 ipsilateral none xxx xxx xxx xxx xxx xxx xxx A R MCA BIF xxx BIF R xxx MULTIPLE xxx OLD MCA-BIF R RUPTURED
sinai.0505.1 sinai 505 1 dat.sinai xxx no F 84 4 ipsilateral none xxx xxx xxx xxx xxx xxx xxx A L ACOM xxx xxx BIF R similar_to_506 MULTIPLE xxx OLD ACOM R RUPTURED
