setwd("/odin1/rdoddaso/aneuDB/baica_analysis/")
ids.batip.R <- read.csv("ids.batip.R.csv")
ids.batip.U <- read.csv("ids.batip.U.csv")
ids.icabif.R <- read.csv("ids.icabif.R.csv")
ids.icabif.U <- read.csv("ids.icabif.U.csv")
ids.batips <- read.csv("id.batips.csv")
ids.icabif <- read.csv("id.icabif.csv")
ids.R <- rbind(ids.batip.R, ids.icabif.R) 
ids.U <- rbind(ids.batip.U, ids.icabif.U) 
hemo.all <- read.csv("hemo.all.csv", sep = " ")
geom.all <- read.csv("geom.all.csv", sep = " ")
View(hemo.all)
View(geom.all)
#All R vs All U Comparison
geom.R <- merge.data.frame(ids.R, geom.all, by = "aid")
hemo.R <- merge.data.frame(ids.R, hemo.all, by = "aid")
geom.U <- merge.data.frame(ids.U, geom.all, by = "aid")
hemo.U <- merge.data.frame(ids.U, hemo.all, by = "aid")
#geom
#aneurysm
mean.avol.R <- mean(geom.R$Avol)
mean.avol.U <- mean(geom.U$Avol)
mean.asize.R <- mean(geom.R$Asize)
mean.asize.U <- mean(geom.U$Asize)
mean.aarea.R <- mean(geom.R$Aarea)
mean.aarea.U <- mean(geom.U$Aarea)
#neck
mean.narea.R <- mean(geom.R$Narea)
mean.narea.U <- mean(geom.U$Narea)
mean.nsize.R <- mean(geom.R$Nsize)
mean.nsize.U <- mean(geom.U$Nsize)
#depth
mean.depth.R <- mean(geom.R$depth)
mean.depth.U <- mean(geom.U$depth)
#AR
mean.ar.R <- mean(geom.R$AR)
mean.ar.U <- mean(geom.U$AR)
#artery sizes
mean.artery.R <- mean(geom.R$artery)
mean.artery.U <- mean(geom.U$artery)
#branches
mean.br1.R <- mean(geom.R$branch1)
mean.br1.U <- mean(geom.U$branch1)
mean.br2.R <- mean(geom.R$branch2)
mean.br2.U <- mean(geom.U$branch2)
#symmmetry
mean.symm.R <- mean(geom.R$symmetry)
mean.symm.U <- mean(geom.U$symmetry)
#Size R
mean.sizer.R <- mean(geom.R$size.ratio)
mean.sizer.U <- mean(geom.U$size.ratio)
#tapers
mean.t1.R <- mean(geom.R$taper1)
mean.t1.U <- mean(geom.U$taper1)
mean.t2.R <- mean(geom.R$taper2)
mean.t2.U <- mean(geom.U$taper2)
mean.meantaper.R <- mean(geom.R$X.taper.)
mean.meantaper.U <- mean(geom.U$X.taper.)

#hemo R vs U

mean.ici.R <- mean(hemo.R$ICI)
mean.ici.U <- mean(hemo.U$ICI)
mean.Q.R <- mean(hemo.R$Q)
mean.Q.U <- mean(hemo.U$Q)
mean.KE.R <- mean(hemo.R$KE)
mean.KE.U <- mean(hemo.U$KE)
mean.SR.R <- mean(hemo.R$SR)
mean.SR.U <- mean(hemo.U$SR)
mean.VE.R <- mean(hemo.R$VE)
mean.VE.U <- mean(hemo.U$VE)
mean.VO.R <- mean(hemo.R$VO)
mean.VO.U <- mean(hemo.U$VO)
mean.VD.R <- mean(hemo.R$VD)
mean.VD.U <- mean(hemo.U$VD)
mean.wssmax.R <- mean(hemo.R$WSSmax)
mean.wssmax.U <- mean(hemo.U$WSSmax)
mean.wssmin.R <- mean(hemo.R$WSSmin)
mean.wssmin.U <- mean(hemo.U$WSSmin)
mean.wss.R <- mean(hemo.R$X.WSS.)
mean.wss.U <- mean(hemo.U$X.WSS.)
mean.lsa.R <- mean(hemo.R$LSA)
mean.lsa.U <- mean(hemo.U$LSA)
mean.sci.R <- mean(hemo.R$SCI)
mean.sci.U <- mean(hemo.U$SCI)
mean.osimax.R <- mean(hemo.R$OSImax)
mean.osimax.U <- mean(hemo.U$OSImax)
mean.osi.R <- mean(hemo.R$X.OSI.)
mean.osi.U <- mean(hemo.U$X.OSI.)
mean.corelen.R <- mean(hemo.R$corelen)
mean.corelen.U <- mean(hemo.U$corelen)
mean.podent.R <- mean(hemo.R$podent)
mean.podent.U <- mean(hemo.U$podent)
mean.podenum.R <- mean(hemo.R$podenum)
mean.podenum.U <- mean(hemo.U$podenum)

# BA vs ICAbif, irrespective of R or U

geom.batip <- merge.data.frame(ids.batips, geom.all, by = "aid")
hemo.batip <- merge.data.frame(ids.batips, hemo.all, by = "aid")
geom.icabif <- merge.data.frame(ids.icabif, geom.all, by = "aid")
hemo.icabif <- merge.data.frame(ids.icabif, hemo.all, by = "aid")

#geom
#aneurysm
mean.avol.b <- mean(geom.batip$Avol)
mean.avol.i <- mean(geom.icabif$Avol)
mean.asize.b <- mean(geom.batip$Asize)
mean.asize.i <- mean(geom.icabif$Asize)
mean.aarea.b <- mean(geom.batip$Aarea)
mean.aarea.i <- mean(geom.icabif$Aarea)
#neck
mean.narea.b <- mean(geom.batip$Narea)
mean.narea.i <- mean(geom.icabif$Narea)
mean.nsize.b <- mean(geom.batip$Nsize)
mean.nsize.i <- mean(geom.icabif$Nsize)
#depth
mean.depth.b <- mean(geom.batip$depth)
mean.depth.i <- mean(geom.icabif$depth)
#AR
mean.ar.b <- mean(geom.batip$AR)
mean.ar.i <- mean(geom.icabif$AR)
#artery sizes
mean.artery.b <- mean(geom.batip$artery)
mean.artery.i <- mean(geom.icabif$artery)
#branches
mean.br1.b <- mean(geom.batip$branch1)
mean.br1.i <- mean(geom.icabif$branch1)
mean.br2.b <- mean(geom.batip$branch2)
mean.br2.i <- mean(geom.icabif$branch2)
#symmmetry
mean.symm.b <- mean(geom.batip$symmetry)
mean.symm.i <- mean(geom.icabif$symmetry)
#Size R
mean.sizer.b <- mean(geom.batip$size.ratio)
mean.sizer.i <- mean(geom.icabif$size.ratio)
#tapers
mean.t1.b <- mean(geom.batip$taper1)
mean.t1.i <- mean(geom.icabif$taper1)
mean.t2.b <- mean(geom.batip$taper2)
mean.t2.i <- mean(geom.icabif$taper2)
mean.meantaper.b <- mean(geom.batip$X.taper.)
mean.meantaper.i <- mean(geom.icabif$X.taper.)

#hemo batip vs icabif

mean.ici.b <- mean(hemo.batip$ICI)
mean.ici.i <- mean(hemo.icabif$ICI)
mean.Q.b <- mean(hemo.batip$Q)
mean.Q.i <- mean(hemo.icabif$Q)
mean.KE.b <- mean(hemo.batip$KE)
mean.KE.i <- mean(hemo.icabif$KE)
mean.SR.b <- mean(hemo.batip$SR)
mean.SR.i <- mean(hemo.icabif$SR)
mean.VE.b <- mean(hemo.batip$VE)
mean.VE.i <- mean(hemo.icabif$VE)
mean.VO.b <- mean(hemo.batip$VO)
mean.VO.i <- mean(hemo.icabif$VO)
mean.VD.b <- mean(hemo.batip$VD)
mean.VD.i <- mean(hemo.icabif$VD)
mean.wssmax.b <- mean(hemo.batip$WSSmax)
mean.wssmax.i <- mean(hemo.icabif$WSSmax)
mean.wssmin.b <- mean(hemo.batip$WSSmin)
mean.wssmin.i <- mean(hemo.icabif$WSSmin)
mean.wss.b <- mean(hemo.batip$X.WSS.)
mean.wss.i <- mean(hemo.icabif$X.WSS.)
mean.lsa.b <- mean(hemo.batip$LSA)
mean.lsa.i <- mean(hemo.icabif$LSA)
mean.sci.b <- mean(hemo.batip$SCI)
mean.sci.i <- mean(hemo.icabif$SCI)
mean.osimax.b <- mean(hemo.batip$OSImax)
mean.osimax.i <- mean(hemo.icabif$OSImax)
mean.osi.b <- mean(hemo.batip$X.OSI.)
mean.osi.i <- mean(hemo.icabif$X.OSI.)
mean.corelen.b <- mean(hemo.batip$corelen)
mean.corelen.i <- mean(hemo.icabif$corelen)
mean.podent.b <- mean(hemo.batip$podent)
mean.podent.i <- mean(hemo.icabif$podent)
mean.podenum.b <- mean(hemo.batip$podenum)
mean.podenum.i <- mean(hemo.icabif$podenum)

# size analysis

all.size <- read.csv("geom.all.csv", sep = " ")
large <- subset(all.size, all.size$size.group == "GIANT" | all.size$size.group == "HUGE" | all.size$size.group == "LARGE")
medium <- subset(all.size, all.size$size.group == "MEDIUM")
small <- subset(all.size, all.size$size.group == "SMALL" | all.size$size.group == "TINY")

large.all <- merge(large, hemo.all)
medium.all <- merge(medium, hemo.all)
small.all <- merge(small, hemo.all)

large.batip <- merge(large.all, hemo.batip)
medium.batip <- merge(medium.all, hemo.batip)
small.batip <- merge(small.all, hemo.batip)

large.icabif <- merge(large.all, hemo.icabif)
medium.icabif <- merge(medium.all, hemo.icabif)
small.icabif <- merge(small.all, hemo.icabif)

mean.large.batip.ici <- mean(large.batip$ICI) 
mean.large.batip.q <- mean(large.batip$Q)
mean.large.batip.ke <- mean(large.batip$KE) 
mean.large.batip.sr <- mean(large.batip$SR) 
mean.large.batip.ve <- mean(large.batip$VE) 
mean.large.batip.vo <- mean(large.batip$VO) 
mean.large.batip.vd <- mean(large.batip$vd) 
mean.large.batip.wssmax <- mean(large.batip$WSSmax) 
mean.large.batip.wssmin <- mean(large.batip$WSSmin) 
mean.large.batip.wssmean <- mean(large.batip$X.WSS.) 
mean.large.batip.lsa <- mean(large.batip$LSA) 
mean.large.batip.sci <- mean(large.batip$SCI) 
mean.large.batip.osimax <- mean(large.batip$OSImax) 
mean.large.batip.osimean <- mean(large.batip$X.OSI.) 
mean.large.batip.corelen <- mean(large.batip$corelen) 
mean.large.batip.podent <- mean(large.batip$podent) 
mean.large.batip.podenum <- mean(large.batip$podenum)

mean.medium.batip.ici <- mean(medium.batip$ICI) 
mean.medium.batip.q <- mean(medium.batip$Q)
mean.medium.batip.ke <- mean(medium.batip$KE) 
mean.medium.batip.sr <- mean(medium.batip$SR) 
mean.medium.batip.ve <- mean(medium.batip$VE) 
mean.medium.batip.vo <- mean(medium.batip$VO) 
mean.medium.batip.vd <- mean(medium.batip$vd) 
mean.medium.batip.wssmax <- mean(medium.batip$WSSmax) 
mean.medium.batip.wssmin <- mean(medium.batip$WSSmin) 
mean.medium.batip.wssmean <- mean(medium.batip$X.WSS.) 
mean.medium.batip.lsa <- mean(medium.batip$LSA) 
mean.medium.batip.sci <- mean(medium.batip$SCI) 
mean.medium.batip.osimax <- mean(medium.batip$OSImax) 
mean.medium.batip.osimean <- mean(medium.batip$X.OSI.) 
mean.medium.batip.corelen <- mean(medium.batip$corelen) 
mean.medium.batip.podent <- mean(medium.batip$podent) 
mean.medium.batip.podenum <- mean(medium.batip$podenum) 

mean.small.batip.ici <- mean(small.batip$ICI) 
mean.small.batip.q <- mean(small.batip$Q)
mean.small.batip.ke <- mean(small.batip$KE) 
mean.small.batip.sr <- mean(small.batip$SR) 
mean.small.batip.ve <- mean(small.batip$VE) 
mean.small.batip.vo <- mean(small.batip$VO) 
mean.small.batip.vd <- mean(small.batip$vd) 
mean.small.batip.wssmax <- mean(small.batip$WSSmax) 
mean.small.batip.wssmin <- mean(small.batip$WSSmin) 
mean.small.batip.wssmean <- mean(small.batip$X.WSS.) 
mean.small.batip.lsa <- mean(small.batip$LSA) 
mean.small.batip.sci <- mean(small.batip$SCI) 
mean.small.batip.osimax <- mean(small.batip$OSImax) 
mean.small.batip.osimean <- mean(small.batip$X.OSI.) 
mean.small.batip.corelen <- mean(small.batip$corelen) 
mean.small.batip.podent <- mean(small.batip$podent) 
mean.small.batip.podenum <- mean(small.batip$podenum) 


mean.large.icabif.ici <- mean(large.icabif$ICI) 
mean.large.icabif.q <- mean(large.icabif$Q)
mean.large.icabif.ke <- mean(large.icabif$KE) 
mean.large.icabif.sr <- mean(large.icabif$SR) 
mean.large.icabif.ve <- mean(large.icabif$VE) 
mean.large.icabif.vo <- mean(large.icabif$VO) 
mean.large.icabif.vd <- mean(large.icabif$vd) 
mean.large.icabif.wssmax <- mean(large.icabif$WSSmax) 
mean.large.icabif.wssmin <- mean(large.icabif$WSSmin) 
mean.large.icabif.wssmean <- mean(large.icabif$X.WSS.) 
mean.large.icabif.lsa <- mean(large.icabif$LSA) 
mean.large.icabif.sci <- mean(large.icabif$SCI) 
mean.large.icabif.osimax <- mean(large.icabif$OSImax) 
mean.large.icabif.osimean <- mean(large.icabif$X.OSI.) 
mean.large.icabif.corelen <- mean(large.icabif$corelen) 
mean.large.icabif.podent <- mean(large.icabif$podent) 
mean.large.icabif.podenum <- mean(large.icabif$podenum)

mean.medium.icabif.ici <- mean(medium.icabif$ICI) 
mean.medium.icabif.q <- mean(medium.icabif$Q)
mean.medium.icabif.ke <- mean(medium.icabif$KE) 
mean.medium.icabif.sr <- mean(medium.icabif$SR) 
mean.medium.icabif.ve <- mean(medium.icabif$VE) 
mean.medium.icabif.vo <- mean(medium.icabif$VO) 
mean.medium.icabif.vd <- mean(medium.icabif$vd) 
mean.medium.icabif.wssmax <- mean(medium.icabif$WSSmax) 
mean.medium.icabif.wssmin <- mean(medium.icabif$WSSmin) 
mean.medium.icabif.wssmean <- mean(medium.icabif$X.WSS.) 
mean.medium.icabif.lsa <- mean(medium.icabif$LSA) 
mean.medium.icabif.sci <- mean(medium.icabif$SCI) 
mean.medium.icabif.osimax <- mean(medium.icabif$OSImax) 
mean.medium.icabif.osimean <- mean(medium.icabif$X.OSI.) 
mean.medium.icabif.corelen <- mean(medium.icabif$corelen) 
mean.medium.icabif.podent <- mean(medium.icabif$podent) 
mean.medium.icabif.podenum <- mean(medium.icabif$podenum) 

mean.small.icabif.ici <- mean(small.icabif$ICI) 
mean.small.icabif.q <- mean(small.icabif$Q)
mean.small.icabif.ke <- mean(small.icabif$KE) 
mean.small.icabif.sr <- mean(small.icabif$SR) 
mean.small.icabif.ve <- mean(small.icabif$VE) 
mean.small.icabif.vo <- mean(small.icabif$VO) 
mean.small.icabif.vd <- mean(small.icabif$vd) 
mean.small.icabif.wssmax <- mean(small.icabif$WSSmax) 
mean.small.icabif.wssmin <- mean(small.icabif$WSSmin) 
mean.small.icabif.wssmean <- mean(small.icabif$X.WSS.) 
mean.small.icabif.lsa <- mean(small.icabif$LSA) 
mean.small.icabif.sci <- mean(small.icabif$SCI) 
mean.small.icabif.osimax <- mean(small.icabif$OSImax) 
mean.small.icabif.osimean <- mean(small.icabif$X.OSI.) 
mean.small.icabif.corelen <- mean(small.icabif$corelen) 
mean.small.icabif.podent <- mean(small.icabif$podent) 
mean.small.icabif.podenum <- mean(small.icabif$podenum) 

