setwd("/odin1/rdoddaso/aneuDB/multi_analysis/mirrors")
mirror.R <- read.csv("mirrors.R.csv",header = F)
mirror.U <- read.csv("mirrors.U.csv",header = F)
#View(mirror.R)
#View(mirror.U)
mirror.wss_inflows <- read.csv("new_dat.csv", stringsAsFactors = FALSE, sep = "")
#View(mirror.wss_inflows)
#dat <- cbind.data.frame(mirror.wss_inflows$aid, mirror.wss_inflows$Inflow, mirror.wss_inflows$Wssnear)
dat1 <- cbind.data.frame(mirror.wss_inflows$aid, mirror.wss_inflows$Inflow)
#View(dat1)
dat2 <- cbind.data.frame(mirror.wss_inflows$aid, mirror.wss_inflows$WSSnear)
#View(dat2)
mirror.inflows.R <- merge(dat1, mirror.R, by.x = "mirror.wss_inflows$aid", by.y = "V1", all = FALSE)
#View(mirror.inflows.R)
mirror.inflows.U <- merge(dat1, mirror.U, by.x = "mirror.wss_inflows$aid", by.y = "V1", all = FALSE)
#View(mirror.inflows.U)
wilcox.test(mirror.inflows.U[[2]],mirror.inflows.R[[2]], paired = TRUE, "two.sided")
#comparison of wss near 
mirror.wssnear.R <- merge(dat2, mirror.R, by.x = "mirror.wss_inflows$aid", by.y = "V1", all = FALSE)
#View(mirror.wssnear.R)
mirror.wssnear.U <- merge(dat2, mirror.U, by.x = "mirror.wss_inflows$aid", by.y = "V1", all = FALSE)
#View(mirror.wssnear.U)
wilcox.test(mirror.wssnear.U[[2]],mirror.wssnear.R[[2]], paired = TRUE, "two.sided")
